# Generated by Django 5.2.9 on 2025-12-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_created_at_alter_menuitem_name'),
        ('orders', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_menu_item_per_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('BILL_REQUESTED', 'Bill Requested'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
    ]
