# Generated by Django 5.2.9 on 2025-12-26 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order'),
        ),
    ]
